### ISSUE TITLE
Can't render

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/create-choo-electron#12]
Right after creating a fresh electron app, running `npm start` result in this, a blank app with two errors. Any idea why? I've not much experience with electron...

![image](https://user-images.githubusercontent.com/5105812/35020935-31b35a10-fb0d-11e7-9ffd-a96e3b4d0635.png)

**Comment by lejeunerenard** [comment]
@YerkoPalma my guess is that you started another server that is bound to `localhost:8080` before running `npm start`. The result is that `bankai` starts but allocates itself to a different port than `8080`.

**Comment by YerkoPalma** [comment]
@lejeunerenard Yeah something like that. Whenever bankai isn't started I get this error (I would expect a 404 or something). Anyway, I think I'll close in favor of #4 since it best describes the same issue.
